// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wncwqqhpomatqjsnxcnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduY3dxcWhwb21hdHFqc254Y25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxODk3MDUsImV4cCI6MjA1Nzc2NTcwNX0.zY9N9omWInkH-m4iTLhdmiZQsh983EyRCGexAt7kW5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);